import Head from "next/head";

const DashboardPage = () => {
    return (
        <>
            <Head>
                <title>User Dashboard</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <h3>User Dashboard</h3>
        </>
    );
};

export default DashboardPage;