import Head from "next/head";

const Title = ({title}) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
    );
};

export default Title;