import Head from 'next/head'
import axios from "axios";
import {API_URL} from "../../config/index";
import EventItem from "../../components/Event-Item/EventItem";

const EventsPage = ({events}) => {
    return (
        <>
            <Head>
                <title>Hottest Party Events</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Upcoming Events</h1>
            {events.length === 0 && <h3>No events to show</h3>}
            {events.map(event => <EventItem key={event.id} event={event}/>)}
        </>
    )
}

export default EventsPage;

export const getStaticProps = async () => {
    const {data} = await axios.get(`${API_URL}/events?_sort=date:ASC`);
    const events = data;

    return {
        props: {events}
    }
}