import Head from 'next/head'
import axios from "axios";
import {API_URL} from "../config/index";
import EventItem from "../components/Event-Item/EventItem";
import Link from "next/link";

const HomePage = ({events}) => {
    return (
        <>
            <Head>
                <title>Hottest Party Events</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <h1>Upcoming Events</h1>
            {events.length === 0 && <h3>No events to show</h3>}
            {events.map(event => <EventItem key={event.id} event={event}/>)}
            {events.length > 0 && <Link href={"/events"}>
                <a className={"btn-secondary"}>View All Events</a>
            </Link>}
        </>
    )
}

export default HomePage;

export const getStaticProps = async () => {
    const {data} = await axios.get(`${API_URL}/events?_sort=date:ASC&_limit=3`);

    return {
        props: {events: data.slice(0, 3)}
    }
}