import Head from 'next/head'
import axios from "axios";
import {API_URL} from "../config/index";
import Home from "../components/Home/Home";

const HomePage = ({events}) => {
    return (
        <>
            <Head>
                <title>Hottest Party Events</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Home events={events} />
        </>
    )
}

export default HomePage;

export const getStaticProps = async () => {
    const {data} = await axios.get(`${API_URL}/events?_sort=date:ASC&_limit=3`);

    return {
        props: {events: data.slice(0, 3)}
    }
}